version: "3"

services:

  runtime-setup:
    image: swift-http-structured-headers:20.04-5.7
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-focal"
        ubuntu_version: "focal"

  unit-tests:
    image: swift-http-structured-headers:20.04-5.7

  test:
    image: swift-http-structured-headers:20.04-5.7

  shell:
    image: swift-http-structured-headers:20.04-5.7

